"""
Codegen.py
----------
Code generator for FlowML.

This module walks the AST produced by the parser and emits valid Python
source code as a string. In other words, FlowML acts as a source-to-source
compiler (transpiler): the generated .py file can run independently with
pandas and scikit-learn installed, and does not need the FlowML runtime.

Pipeline:
    .fml source -> Lexer -> Parser -> AST -> CodeGenerator -> .py file

Usage (internal):
    from .codegen import CodeGenerator
    generator = CodeGenerator()
    python_source = generator.generate(ast)

Usage (CLI via main.py):
    python main.py script.fml --compile
    # produces script.py
"""

from __future__ import annotations

from typing import Any

from .ast_nodes import (
    AssignmentStatement,
    BinaryExpression,
    BoolLiteral,
    DropStatement,
    EvaluateStatement,
    FloatLiteral,
    FunctionCall,
    FunctionDefinition,
    IfStatement,
    LoadStatement,
    ModelStatement,
    NormalizeStatement,
    NumberLiteral,
    PrintStatement,
    Program,
    ReturnStatement,
    SplitStatement,
    StringLiteral,
    TrainStatement,
    UnaryExpression,
    Variable,
    WhileStatement,
)


# ---------------------------------------------------------------------------
# Import tracking maps
# ---------------------------------------------------------------------------
# Step 1: map symbolic keys to real import lines
# Step 2: collect needed keys while walking the AST
# Step 3: emit only the imports that were actually needed

ML_IMPORTS = {
    "pandas": "import pandas as pd",
    "StandardScaler": "from sklearn.preprocessing import StandardScaler",
    "train_test_split": "from sklearn.model_selection import train_test_split",
    "LabelEncoder": "from sklearn.preprocessing import LabelEncoder",
    # Models
    "LogisticRegression": "from sklearn.linear_model import LogisticRegression",
    "LinearRegression": "from sklearn.linear_model import LinearRegression",
    "Ridge": "from sklearn.linear_model import Ridge",
    "Lasso": "from sklearn.linear_model import Lasso",
    "RandomForest": "from sklearn.ensemble import RandomForestClassifier",
    "SVM": "from sklearn.svm import SVC",
    "KNN": "from sklearn.neighbors import KNeighborsClassifier",
    "NaiveBayes": "from sklearn.naive_bayes import GaussianNB",
    "KMeans": "from sklearn.cluster import KMeans",
}


# FlowML model name -> sklearn class
MODEL_CLASS = {
    "LogisticRegression": "LogisticRegression",
    "LinearRegression": "LinearRegression",
    "Ridge": "Ridge",
    "Lasso": "Lasso",
    "RandomForest": "RandomForestClassifier",
    "SVM": "SVC",
    "KNN": "KNeighborsClassifier",
    "NaiveBayes": "GaussianNB",
    "KMeans": "KMeans",
}


# FlowML hyperparameter names -> sklearn constructor names
PARAM_MAP = {
    "trees": "n_estimators",
    "neighbors": "n_neighbors",
    "clusters": "n_clusters",
    "alpha": "alpha",
}


class CodeGenerator:
    """
    Walk the FlowML AST and build a complete Python source file.

    Design:
    - Statement methods emit full lines into an internal buffer.
    - Expression methods return expression strings.
    - Indentation is tracked explicitly via an integer level.
    """

    def __init__(self) -> None:
        # Output buffer
        self._lines: list[str] = []
        self._indent_level: int = 0

        # Import tracking
        self._needed_imports: set[str] = set()

        # Deferred normalization state
        # We mirror the evaluator behavior by waiting until split to apply scaling.
        self._normalize_cols: list[str] = []

    # -----------------------------------------------------------------------
    # Public entry point
    # -----------------------------------------------------------------------

    def generate(self, program: Program) -> str:
        """
        Generate a complete Python file from a FlowML Program node.

        Args:
            program: Root AST node containing all top-level statements.

        Returns:
            Python source code as one newline-terminated string.
        """
        # Step 1: reset generator state for a fresh run.
        self._reset_state()

        # Step 2: generate body lines from each top-level statement.
        for statement in program.statements:
            self._gen_statement(statement)

        # Step 3: build final file sections (header + imports + body).
        header_lines = [
            "# Generated by FlowML compiler",
            "# Run with: python <this_file>.py",
            "",
        ]
        import_lines = self._build_imports()

        final_lines = list(header_lines)
        final_lines.extend(import_lines)
        if import_lines:
            final_lines.append("")
        final_lines.extend(self._lines)

        return "\n".join(final_lines) + "\n"

    def _reset_state(self) -> None:
        """Clear per-run state before generating a new file."""
        self._lines = []
        self._needed_imports = set()
        self._normalize_cols = []
        self._indent_level = 0

    # -----------------------------------------------------------------------
    # Indentation helpers
    # -----------------------------------------------------------------------

    def _current_indent(self) -> str:
        """Return indentation spaces for the current nesting level."""
        return "    " * self._indent_level

    def emit(self, line: str) -> None:
        """Append one line to the output using current indentation."""
        self._lines.append(self._current_indent() + line)

    def _emit_block(self, statements: list[Any]) -> None:
        """
        Emit a list of nested statements.

        We increase indent once for the block, emit all statements, and then
        restore indent so parent code continues at the original level.
        """
        self._indent_level += 1
        for statement in statements:
            self._gen_statement(statement)
        self._indent_level -= 1

    # -----------------------------------------------------------------------
    # Import helpers
    # -----------------------------------------------------------------------

    def _need(self, *keys: str) -> None:
        """Mark one or more import keys as required by generated code."""
        for key in keys:
            self._needed_imports.add(key)

    def _build_imports(self) -> list[str]:
        """
        Build import lines in a stable, readable order.

        Returns:
            Ordered list of import statements.
        """
        ordered_keys = [
            "pandas",
            "StandardScaler",
            "train_test_split",
            "LabelEncoder",
            "LogisticRegression",
            "LinearRegression",
            "Ridge",
            "Lasso",
            "RandomForest",
            "SVM",
            "KNN",
            "NaiveBayes",
            "KMeans",
        ]

        import_lines: list[str] = []
        for key in ordered_keys:
            if key in self._needed_imports:
                import_lines.append(ML_IMPORTS[key])
        return import_lines

    # -----------------------------------------------------------------------
    # Statement dispatcher
    # -----------------------------------------------------------------------

    def _gen_statement(self, node: Any) -> None:
        """
        Dispatch statement nodes to type-specific generator methods.

        Unknown node types become warning comments so generation still
        succeeds and the output remains inspectable.
        """
        method_name = f"_gen_{type(node).__name__}"
        method = getattr(self, method_name, self._gen_unknown)
        method(node)

    def _gen_unknown(self, node: Any) -> None:
        """Fallback for unsupported nodes."""
        self.emit(f"# WARNING: unsupported node {type(node).__name__}")

    # -----------------------------------------------------------------------
    # Expression generator
    # -----------------------------------------------------------------------

    def _gen_expr(self, node: Any) -> str:
        """
        Convert an expression AST node into a Python expression string.

        Args:
            node: Any expression-type AST node.

        Returns:
            A Python expression string (not a full line).
        """
        # Step 1: literals and identifiers
        if isinstance(node, NumberLiteral):
            return str(node.value)

        if isinstance(node, FloatLiteral):
            # repr preserves full float precision better than str
            return repr(node.value)

        if isinstance(node, StringLiteral):
            # repr safely handles quotes/escapes in output code
            return repr(node.value)

        if isinstance(node, BoolLiteral):
            return "True" if node.value else "False"

        if isinstance(node, Variable):
            return node.name

        # Step 2: unary expressions
        if isinstance(node, UnaryExpression):
            operand = self._gen_expr(node.operand)
            return f"(-{operand})"

        # Step 3: binary expressions
        if isinstance(node, BinaryExpression):
            left_expr = self._gen_expr(node.left)
            right_expr = self._gen_expr(node.right)
            operator = node.operator

            # FlowML evaluator currently uses integer-style division.
            # Emit '//' to match evaluator behavior.
            if operator == "/":
                return f"({left_expr} // {right_expr})"

            return f"({left_expr} {operator} {right_expr})"

        # Step 4: function calls used inside larger expressions
        if isinstance(node, FunctionCall):
            arg_exprs: list[str] = []
            for arg in node.arguments:
                arg_exprs.append(self._gen_expr(arg))
            joined_args = ", ".join(arg_exprs)
            return f"{node.name}({joined_args})"

        # Step 5: unknown expression fallback
        return f"# UNKNOWN_EXPR({type(node).__name__})"

    # -----------------------------------------------------------------------
    # General statement generators
    # -----------------------------------------------------------------------

    def _gen_AssignmentStatement(self, node: AssignmentStatement) -> None:
        """Generate: <name> = <expression>."""
        expression_text = self._gen_expr(node.expression)
        self.emit(f"{node.variable.name} = {expression_text}")

    def _gen_PrintStatement(self, node: PrintStatement) -> None:
        """Generate print or println style output."""
        expression_text = self._gen_expr(node.expression)

        if node.newline:
            self.emit(f"print({expression_text})")
            return

        self.emit(f"print({expression_text}, end='')")

    def _gen_IfStatement(self, node: IfStatement) -> None:
        """Generate if/else blocks."""
        condition_text = self._gen_expr(node.condition)
        self.emit(f"if {condition_text}:")
        self._emit_block(node.then_branch)

        if node.else_branch:
            self.emit("else:")
            self._emit_block(node.else_branch)

    def _gen_WhileStatement(self, node: WhileStatement) -> None:
        """Generate while loops."""
        condition_text = self._gen_expr(node.condition)
        self.emit(f"while {condition_text}:")
        self._emit_block(node.body)

    def _gen_FunctionDefinition(self, node: FunctionDefinition) -> None:
        """Generate function definitions with a pass fallback for empty bodies."""
        params_text = ", ".join(node.parameters)
        self.emit(f"def {node.name}({params_text}):")

        if node.body:
            self._emit_block(node.body)
            return

        self._indent_level += 1
        self.emit("pass")
        self._indent_level -= 1

    def _gen_ReturnStatement(self, node: ReturnStatement) -> None:
        """Generate return statements with optional expression."""
        if node.expression is None:
            self.emit("return")
            return

        expression_text = self._gen_expr(node.expression)
        self.emit(f"return {expression_text}")

    def _gen_FunctionCall(self, node: FunctionCall) -> None:
        """Generate function calls used as stand-alone statements."""
        arg_exprs: list[str] = []
        for arg in node.arguments:
            arg_exprs.append(self._gen_expr(arg))
        joined_args = ", ".join(arg_exprs)
        self.emit(f"{node.name}({joined_args})")

    # -----------------------------------------------------------------------
    # ML statement generators
    # -----------------------------------------------------------------------

    def _gen_LoadStatement(self, node: LoadStatement) -> None:
        """
        FlowML:
            load "iris.csv";
        Python:
            import pandas as pd
            _df = pd.read_csv("iris.csv")
        """
        self._need("pandas")
        self.emit(f"_df = pd.read_csv({repr(node.filename)})")

    def _gen_DropStatement(self, node: DropStatement) -> None:
        """
        FlowML:
            drop columns "id", "name";
        Python:
            _df = _df.drop(columns=["id", "name"])
        """
        columns_repr = repr(node.column_names)
        self.emit(f"_df = _df.drop(columns={columns_repr})")

    def _gen_NormalizeStatement(self, node: NormalizeStatement) -> None:
        """
        FlowML:
            normalize columns "a", "b";

        Behavior:
            Store columns now and apply scaling later in split().
            This avoids data leakage by fitting on train and transforming test.
        """
        self._normalize_cols = list(node.column_names)
        self.emit(f"# normalize columns {node.column_names} - applied after split")

    def _gen_SplitStatement(self, node: SplitStatement) -> None:
        """
        FlowML:
            split data into train=0.8 test=0.2;

        Python summary:
            1) Separate features/target
            2) Train/test split
            3) Optional deferred normalization
            4) Bind train_set and test_set
        """
        self._need("train_test_split")

        # Step 1: split dataframe into X and y
        self.emit("_X = _df.iloc[:, :-1].copy()")
        self.emit("_y = _df.iloc[:, -1].copy()")

        # Step 2: perform train/test split
        self.emit(
            "_X_train, _X_test, _y_train, _y_test = "
            f"train_test_split(_X, _y, test_size={repr(node.test)})"
        )

        # Step 3: apply deferred normalization if requested earlier
        if self._normalize_cols:
            self._need("StandardScaler")
            columns_repr = repr(self._normalize_cols)
            self.emit("_scaler = StandardScaler()")
            self.emit(
                f"_X_train[{columns_repr}] = "
                f"_scaler.fit_transform(_X_train[{columns_repr}])"
            )
            self.emit(
                f"_X_test[{columns_repr}] = "
                f"_scaler.transform(_X_test[{columns_repr}])"
            )

            # Clear once emitted so later split nodes do not reuse old columns.
            self._normalize_cols = []

        # Step 4: keep tuple names aligned with evaluator behavior
        self.emit("train_set = (_X_train, _y_train)")
        self.emit("test_set = (_X_test, _y_test)")

    def _gen_ModelStatement(self, node: ModelStatement) -> None:
        """
        FlowML:
            model RandomForest trees=100;
        Python:
            from sklearn.ensemble import RandomForestClassifier
            _model = RandomForestClassifier(n_estimators=100)
        """
        model_name = node.model_name
        if model_name not in MODEL_CLASS:
            self.emit(f"# ERROR: unknown model '{model_name}'")
            return

        self._need(model_name)
        class_name = MODEL_CLASS[model_name]

        # Translate FlowML parameter names to sklearn names.
        mapped_params: dict[str, Any] = {}
        raw_params = node.params or {}
        for param_name, param_value in raw_params.items():
            sklearn_name = PARAM_MAP.get(param_name, param_name)
            mapped_params[sklearn_name] = param_value

        if not mapped_params:
            self.emit(f"_model = {class_name}()")
            return

        pieces: list[str] = []
        for key, value in mapped_params.items():
            pieces.append(f"{key}={repr(value)}")
        params_text = ", ".join(pieces)
        self.emit(f"_model = {class_name}({params_text})")

    def _gen_TrainStatement(self, node: TrainStatement) -> None:
        """
        FlowML:
            train on train_set;
        Python:
            _X_tr, _y_tr = train_set
            _model.fit(_X_tr, _y_tr)
        """
        self.emit(f"_X_tr, _y_tr = {node.dataset}")
        self.emit("_model.fit(_X_tr, _y_tr)")

    def _gen_EvaluateStatement(self, node: EvaluateStatement) -> None:
        """
        FlowML:
            accuracy = evaluate on test_set;
        Python:
            _X_te, _y_te = test_set
            accuracy = _model.score(_X_te, _y_te)
        """
        self.emit(f"_X_te, _y_te = {node.dataset}")
        self.emit(f"{node.result_var} = _model.score(_X_te, _y_te)")
